# Case Study: Movie Data Analysis Exercises

In [2]:
import pandas as pd

In this exercise notebook you will have the opportunity to load the MovieLens database and perform additional analysis.

First let's load the data into a Pandas Dataframe:

In [3]:
from google.colab import drive
drive.mount ('/content/drive')
movies = pd.read_csv('drive/My Drive/Notebook08/movies.csv')
ratings = pd.read_csv('drive/My Drive/Notebook08/ratings.csv')

Mounted at /content/drive

In [4]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [5]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [6]:
#Remember the two different ways of accessing dataframe columns, either dot notation or bracket notation.
#The line below finds the average rating of movie 2 using dot notation.
ratings[ratings.movieId == 2].rating.mean()

3.2515271586594023

In [7]:
#The line below finds the average rating of movie 2 using bracket notation.
ratings[ratings['movieId']==2]['rating'].mean()

3.2515271586594023

We will use the dot notation for the rest of this notebook where possible for improved clarity.

## Exercise 1: Find the Minimum Rating

Let's start by computing the minimum rating.

In the next cell, define the `min_rating` variable to be the minimum rating across all of the DataFrame:

In [8]:
min_rating = None
### BEGIN SOLUTION
### YOUR CODE HERE
min_rating = ratings.rating.min()

### END SOLUTION

In [9]:
# DO NOT MODIFY

assert isinstance(min_rating, float), "Try again, make sure you are taking the min of just 1 column"
assert abs(min_rating - 0.5) < .01, "Try again, the minimum should be 0.5"

## Exercise 2: Find the Mean Rating of a Movie

The movie **Toy Story** has `movieId` 1. Find out the mean rating for Toy Story. For this exercise you just need to use the `ratings` DataFrame. Call this mean rating "toy_story_rating".

In [10]:
toy_story_rating = None
### BEGIN SOLUTION
### YOUR CODE HERE!
# toy_story_rating = (ratings.ratings.movieId == 1).mean()
toy_story_rating = ratings[ratings.movieId == 1].rating.mean()

### END SOLUTION

In [11]:
assert abs(toy_story_rating - 3.89) < 0.01, "Try again, select only the rows where the movieId is equal to 1"

## Setting an Index for the Movies DataFrame

Movies has one column `movieId` that is a natural way of uniquely identifying each row, when that is the case, it is useful to turn that into an index.

In [12]:
movies = movies.set_index("movieId")
movies.head()

,title,genres
movieId,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy

In [13]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

Ratings instead does not have a row identifier, both `userId` and `movieId` can appear multiple times, therefore there is no good candidate for an index, so we can just leave the default integer indexing.

## Exercise 3: Year with Maximum  Average Rating

Find which **year** has the maximum average rating, **not** the maximum value of the average, but the **year** when it occurs. We will first add the year of the rating to the ratings dataframe below.

HINT: First use .groupby().mean() to group ratings by year and compute the mean rating for each year. Then sort this DataFrame by mean rating using the sort_values() method. Use the 'ascending=False' option to sort_values so that high ratings will come first. The year with the maximum average rating should then be the first index of this sorted DataFrame.

Or, if you want to learn a new command you can use the `idxmax` method to get the index of the maximum value instead of sorting, look at its documentation on the pandas website, https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.idxmax.html

First we want to convert the timestamp into a datetime object so that we can add year of rating to the dataframe.

In [14]:
# DO NOT MODIFY. This adds year to the ratings data frame from the timestamp.
# Note that this is the year that the rating was given, NOT the year of the movie.
ratings['year'] = pd.to_datetime(ratings.timestamp, unit='s').dt.year
ratings.head()

   userId  movieId  rating   timestamp  year
0       1      296     5.0  1147880044  2006
1       1      306     3.5  1147868817  2006
2       1      307     5.0  1147868828  2006
3       1      665     5.0  1147878820  2006
4       1      899     3.5  1147868510  2006

In [15]:
def find_year_with_max_avg(ratings):
    """Function to find the year with the largest average rating in ratings"""
    ### BEGIN SOLUTION
    ### YOUR CODE HERE!
    # Group by year and compute the mean rating for each year
    average_rating = ratings[['rating', 'year']].groupby('year').mean()
    return average_rating.idxmax(numeric_only=True)['rating']  # Extract the year

    #  Sort the DataFrame by mean rating in descending order

    # sorted_ratings = average_rating.sort_values(by='rating', ascending=False)


    # The year with the maximum average rating is the first index of the sorted DataFrame

    # max_avg_year = sorted_ratings.index[0]
    # return max_avg_year

    ### END SOLUTION

In [16]:
print(find_year_with_max_avg(ratings))

1995

In [17]:
assert find_year_with_max_avg(ratings) == 1995, "Wrong year identified, try again!"

# Exercise 4: Identify Popular Movies

Next we would like to only consider movies that have a significant number of ratings. This task is complicated by the fact that movies and ratings are in 2 different DataFrames and we want to filter the `movies` DataFrame based on a statistic from the `ratings` DataFrame.

First let's compute the number of ratings per movie:

In [18]:
number_of_ratings = ratings.movieId.value_counts()
number_of_ratings.head()

movieId
356     81491
318     81482
296     79672
593     74127
2571    72674
Name: count, dtype: int64

Now we want to filter this pandas Series object and keep only the rows where the count is larger or equal to 100.
We don't want to pollute our analysis with movies with a tiny number of reviews. Call the filtered series "number_of_ratings_of_popular_movies".

In [19]:
number_of_ratings_of_popular_movies = None
### BEGIN SOLUTION
### YOUR CODE HERE!
number_of_ratings_of_popular_movies = number_of_ratings[number_of_ratings >= 100]

### END SOLUTION

In [20]:
assert len(number_of_ratings_of_popular_movies) == 10326, "Try again, check that movies with 100 ratings are accepted"

Finally we want to use the `reindex` function to change the index of movies, this will create a new DataFrame with a new index that contains the movieId of only the most popular movies.

The value of all the rows of `movies` that have the same movieId will be copied over to the new `all_popular_movies` dataframe, the rest will be discarded.

In [21]:
all_popular_movies = movies.reindex(number_of_ratings_of_popular_movies.index).sort_index()
all_popular_movies.head()

,title,genres
movieId,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
3,Grumpier Old Men (1995),Comedy|Romance
4,Waiting to Exhale (1995),Comedy|Drama|Romance
5,Father of the Bride Part II (1995),Comedy

# Exercise 5: Filter by Genre

Implement a general function that filters movies by genres. Include the movie as long as the genre is at least one of the generes mentioned in the genres column of the dataframe. It does not have to be an exact match to the entire genres entry for that movie. HINT: Your solution should use str.contains. The function should return the filtered dataframe.

In [22]:
def filter_by_genre(input_movies, genre):
    """Return only movies of a specific genre"""
    ### BEGIN SOLUTION
    ### YOUR CODE HERE!
    return input_movies[input_movies.genres.str.contains(genre)]


    ### END SOLUTION

Then let's apply it to the `popular_movies` dataset to retain only the "Fantasy" movies:

In [23]:
fantasy_movies = filter_by_genre(all_popular_movies, "Fantasy")

In [24]:
assert len(fantasy_movies) == 742, """Try again, Make sure you are filtering the popular movies"""

# Exercise 6: Join Movies and Ratings

Let's create a single `DataFrame` that contains both titles and mean ratings of the popular fantasy movies.

Titles are only available in the `movies` `DataFrame`, while ratings are only available in the `ratings` `DataFrame`. We would like to create a single DataFrame that includes the title and the mean rating.

First create the `mean_ratings` dataframe by computing the mean rating for each movieId:

In [25]:
mean_ratings = ratings[['movieId','rating']].groupby('movieId').mean()
mean_ratings.head()

           rating
movieId
1        3.893708
2        3.251527
3        3.142028
4        2.853547
5        3.058434

In [26]:
fantasy_movies.head()

,title,genres
movieId,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,Jumanji (1995),Adventure|Children|Fantasy
29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi
44,Mortal Kombat (1995),Action|Adventure|Fantasy
60,"Indian in the Cupboard, The (1995)",Adventure|Children|Fantasy

Now properly merge the mean_ratings and fantasy_movies dataframes to create a new "fantasy_movies_with_ratings" dataframe. There should be one extra column of 'rating' added to the fantasy_movies dataframe after the merge.

In [27]:
fantasy_movies_with_ratings = None
### BEGIN SOLUTION
### YOUR CODE HERE!
fantasy_movies_with_ratings = pd.merge(fantasy_movies, mean_ratings, on='movieId')
### END SOLUTION

In [28]:
fantasy_movies_with_ratings.head()

,title,genres,rating
movieId,,,
1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.893708
2,Jumanji (1995),Adventure|Children|Fantasy,3.251527
29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,3.936725
44,Mortal Kombat (1995),Action|Adventure|Fantasy,2.654624
60,"Indian in the Cupboard, The (1995)",Adventure|Children|Fantasy,3.095889

In [29]:
assert fantasy_movies_with_ratings.loc[7164].title.startswith("Peter"), "Try again, missing or wrong title"

In [30]:
assert abs(fantasy_movies_with_ratings.loc[7164].rating - 3.39) < 0.01 , "Try again, missing or wrong rating"

# Exercise 7: Find the Title of the Highest Rated Fantasy Movie

Finally, we will use the sort_values() method to sort the fantasy_movies_with_ratings dataframe by ratings, we use ascending=False in the call to sort_values to get the highest ratings first. Then you should pull out the title of the highest rated fantasy movie from this sorted data frame. Store this title in the variable "highest_rated_fantasy_movie".

In [31]:
sorted_fantasies = fantasy_movies_with_ratings.sort_values(by='rating', ascending=False)
sorted_fantasies.head()

,title,genres,rating
movieId,,,
5618,Spirited Away (Sen to Chihiro no kamikakushi) ...,Adventure|Animation|Fantasy,4.212267
172577,Last Year's Snow Was Falling (1983),Animation|Children|Comedy|Fantasy,4.200000
5971,My Neighbor Totoro (Tonari no Totoro) (1988),Animation|Children|Drama|Fantasy,4.152463
1136,Monty Python and the Holy Grail (1975),Adventure|Comedy|Fantasy,4.147655
3000,Princess Mononoke (Mononoke-hime) (1997),Action|Adventure|Animation|Drama|Fantasy,4.138094

In [32]:
highest_rated_fantasy_movie = None
### BEGIN SOLUTION
### YOUR CODE HERE!
highest_rated_fantasy_movie = sorted_fantasies.iloc[0]['title']
### END SOLUTION

In [33]:
highest_rated_fantasy_movie

'Spirited Away (Sen to Chihiro no kamikakushi) (2001)'

In [34]:
assert 'Spirited' in highest_rated_fantasy_movie, "Try again"